name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Check code formatting
      run: npm run format -- --check
    
    - name: Type check
      run: npx tsc --noEmit
    
    - name: Build project
      run: npm run build
    
    - name: Run tests (if available)
      run: npm test || echo "No tests found"
      continue-on-error: true
  
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true

  block-merge-on-failure:
    runs-on: ubuntu-latest
    needs: [test-and-build, security-scan]
    if: failure()
    steps:
    - name: Block merge on failure
      run: |
        echo "❌ Pipeline failed. Merge blocked."
        exit 1 